name: "Build Release"
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2, with: { fetch-depth: 0 } }
      - {
          name: "Set up JDK 16",
          uses: actions/setup-java@v2,
          with: { distribution: "adopt", java-version: "16" },
        }
      - {
          name: "Build with Gradle",
          id: build,
          env:
            {
              MAVEN_PASSWORD: "${{secrets.MAVEN_PASSWORD}}",
              MAVEN_URL: "${{secrets.MAVEN_URL}}",
              MAVEN_USER: "${{secrets.MAVEN_USER}}",
              USE_ALPHAS: false,
            },
          run: "chmod +x gradlew && ./gradlew setupGithubActions build publish",
        }
      - name: "Create a Release"
        id: create_release
        uses: meeDamian/github-release@2.0
        with:
          files: "fabric/build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-fabric.jar forge/build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-forge.jar"
          gzip: false
          name: "${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Upload Fabric to CurseForge"
        uses: itsmeow/curseforge-upload@master
        with:
          changelog: "Changelog not added yet..."
          display_name: "${{ steps.build.outputs.curse_title }} [Fabric]"
          file_path: "fabric/build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-fabric.jar"
          game_endpoint: minecraft
          relations: "${{ steps.build.outputs.curse_relations_fabric }}"
          game_versions: "${{ steps.build.outputs.curse_versions_fabric }}"
          project_id: "${{ steps.build.outputs.project_id }}"
          release_type: release
          token: "${{ secrets.CF_API_TOKEN }}"
      - name: "Upload Forge to CurseForge"
        uses: itsmeow/curseforge-upload@master
        with:
          changelog: "Changelog not added yet..."
          display_name: "${{ steps.build.outputs.curse_title }} [Forge]"
          file_path: "forge/build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-forge.jar"
          game_endpoint: minecraft
          relations: "${{ steps.build.outputs.curse_relations_forge }}"
          game_versions: "${{ steps.build.outputs.curse_versions_forge }}"
          project_id: "${{ steps.build.outputs.project_id }}"
          release_type: release
          token: "${{ secrets.CF_API_TOKEN }}"
      - name: "Build Success"
        id: build-success
        uses: itsmeow/webhook-action@master
        env:
          WEBHOOK_URL: "${{ secrets.DISCORD_WEBHOOK_URL }}"
          data: '{"embeds":[{"title":"${{ steps.build.outputs.modid }} Release Build","url":"https://github.com/${{ github.repository }}/releases/tag/${{ steps.build.outputs.version }}","description":"Tag: ${{ steps.build.outputs.version }}\nStatus: Successful","color":65280,"author":{"name":"${{ github.event.user.login }}","url":"${{ github.event.user.html_url }}","icon_url":"${{ github.event.user.avatar_url }}"}}]}'
      - name: "Build Fail"
        id: build-fail
        uses: itsmeow/webhook-action@master
        if: failure()
        env:
          WEBHOOK_URL: '${{ secrets.DISCORD_WEBHOOK_URL }}\'
          data: '{"embeds":[{"title":"${{ steps.build.outputs.modid }} Release Build","url":"https://github.com/${{ github.repository }}/releases/tag/${{ steps.build.outputs.version }}","description":"Tag: ${{ steps.build.outputs.version }}\nStatus: Failed","color":16711680,"author":{"name":"${{ github.event.user.login }}","url":"${{ github.event.user.html_url }}","icon_url":"${{ github.event.user.avatar_url }}"}}]}'
